<?php

namespace Coyote\ApiBundle\Entity;

use Doctrine\ORM\EntityRepository;
use CrEOF\Spatial\DBAL\Types\Geometry\PointType;
use CrEOF\Spatial\PHP\Types\Geometry\Point;

/**
 * PositionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PositionRepository extends EntityRepository
{
    public function test()
    {
        $db = $this->getDoctrine()->getManager()->getConnection();
        $sql = "SELECT ST_Distance(
              ST_GeographyFromText('POINT(-118.4079 33.9434)'),
              ST_GeographyFromText('POINT(2.5559 49.0083)')
              );";
        //$sql = "SELECT st_extent(the_geom) FROM (" . implode(" UNION ", $sqlPart) . ") AS foo";
        $box = $db->query($sql)->fetchColumn();
        return $box;


        /*
            Select st_distance('POINT(48.427395 -4.4333391)'::geography,
  'POINT(48.427502 -4.4312842)'::geography) AS d;
  */
    //$conn = $this->get('pgsql');
    $qb = $this->_em->createQueryBuilder();

    /*
      SELECT ST_Distance(
  ST_GeographyFromText('POINT(-118.4079 33.9434)'),
  ST_GeographyFromText('POINT(2.5559 49.0083)')
  );



    */

        /*$qb = $this->_em->createQuery(
            "SELECT ST_Distance(
  st_geomfromtext('POINT(-118.4079 33.9434)'),
  st_geomfromtext('POINT(2.5559 49.0083)')
  )as d FROM spatial_ref_sys;"
            );
*/
            $qb = $this->_em->createQuery("
    			SELECT  ST_Distance(
                  st_geomfromtext('POINT(-118.4079 33.9434)'),
                  st_geomfromtext('POINT(2.5559 49.0083)')
                  ) FROM CoyoteApiBundle:Position p ");


	/*$p1 = new Point(-118.4079, 33.9434);
        $p2 = new Point(2.5559, 49.0083);

	$qb = $this->_em->createQueryBuilder()
            ->select('ST_Distance(ST_GeomFromText(:p1), ST_GeomFromText(:p2))')
            ->setParameter('p1', $p1, 'point')
            ->setParameter('p2', $p2, 'point')
            ->from('CoyoteApiBundle:Position', 'p')
	    ->getQuery();
*/
        $return = $qb->getResult();
    }
}
